### ISSUE TITLE
Feat 🛠️ API to integrate with Codium.

### ISSUE THREAD

**Issue by kierun** [murtuzaalisurti/better#7]
[Codium](https://codeium.com/) support would be greatly appreciated.

Please let me know if you need some help with testing, as I have some free Pro use credits.

**Comment by murtuzaalisurti** [comment]
seems like codium has their own code review tool https://codeium.com/forge, and I can't seem to find an API exposed for codium, do you know one?

**Comment by murtuzaalisurti** [comment]
let's close it for now, we can open it once we find something interesting
