### ISSUE TITLE
 Feat 🛠️ API to integrate with Le Chat / Mistral

### ISSUE THREAD

**Issue by kierun** [murtuzaalisurti/better#8]
[Le Chat/Mistral](https://docs.mistral.ai/api/) support would be nice to have.

Again, if you need help testing, I have a few credits there…

**Comment by murtuzaalisurti** [comment]
yeah that's a great idea @kierun, do you know any specific models which work best with text and code generation? ref: https://docs.mistral.ai/getting-started/models/models_overview/

**Comment by kierun** [comment]
I use Mistral mostly for text. For code, Codeium is great
